---
- name: Ensure Apache is installed
  apt:
    name: apache2
    state: present
    update_cache: yes
  become: yes
  
- name: Ensure Apache is running and enabled
  service:
    name: apache2
    state: started
    enabled: yes
  become: yes  
